# alias file. This is sourced in .bashrc
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias ls='ls --color=auto'
alias doc='docker'
alias psqlpoop='psql -U postgres -d postgres'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'
#alias java='openjdk.java'
alias python='python3'
alias pve='source ~/PVE/bin/activate'
alias dpve='deactivate'
alias al='cd ~/Documents/MSU/CS_4050/'
alias data='cd ~/Documents/MSU/MTH_3270/'
alias db='cd ~/Documents/MSU/CS_3810/'
alias met='cd ~/Documents/MSU/MET_1040/'
alias update='sudo apt-get update && sudo apt upgrade && sudo snap refresh && sudo apt update'
alias opn='open . && exit'
alias treed='tree -d -L 2'
alias treea='tree -a -L 2'

